export type QrKind="website"|"social"|"text"|"wifi"|"email"|"phone"|"sms"|"whatsapp"|"contact";
export type SocialService="instagram"|"facebook"|"linkedin"|"youtube"|"tiktok"|"x"|"whatsapp"|"github"|"pinterest"|"threads"|"custom";
export type QrPayloadInput={kind:QrKind;value?:string;socialService?:SocialService;recipient?:string;message?:string;subject?:string;wifiName?:string;wifiPassword?:string;wifiSecurity?:string;wifiHidden?:boolean;contactName?:string;contactEmail?:string;contactPhone?:string};
const escapeWifi=(value:string)=>value.replace(/([\\;,:"])/g,"\\$1");
const escapeContact=(value:string)=>value.replace(/([\\;,])/g,"\\$1").replace(/\r?\n/g,"\\n");
const socialBases:Record<SocialService,string>={instagram:"instagram.com/",facebook:"facebook.com/",linkedin:"linkedin.com/in/",youtube:"youtube.com/@",tiktok:"tiktok.com/@",x:"x.com/",whatsapp:"wa.me/",github:"github.com/",pinterest:"pinterest.com/",threads:"threads.net/@",custom:""};
export function socialProfilePrefix(service:SocialService){return socialBases[service]}
export function normalizeSocialProfileLink(service:SocialService,input:string){const value=input.trim();if(!value)return "";if(/^[a-z][a-z0-9+.-]*:\/\//i.test(value))return value.replace(/^http:\/\//i,"https://");const base=socialBases[service],withoutWww=value.replace(/^www\./i,"");if(withoutWww.toLowerCase().startsWith(base))return `https://${withoutWww}`;if(service==="custom")return `https://${value}`;const handle=value.replace(/^@|^\/+|\/+$/g,"");return `https://${base}${handle}`}
export function buildQrPayload(input:QrPayloadInput){const value=input.value?.trim()??"",recipient=input.recipient?.trim()??"",message=input.message?.trim()??"",subject=input.subject?.trim()??"";if(input.kind==="text")return value;if(input.kind==="website")return value&&!/^[a-z][a-z0-9+.-]*:/i.test(value)?`https://${value}`:value;if(input.kind==="social")return normalizeSocialProfileLink(input.socialService??"custom",value);if(input.kind==="wifi")return input.wifiName?.trim()?`WIFI:T:${input.wifiSecurity??"WPA"};S:${escapeWifi(input.wifiName.trim())};P:${input.wifiSecurity==="nopass"?"":escapeWifi(input.wifiPassword??"")};H:${input.wifiHidden?"true":"false"};;`:"";if(input.kind==="email")return recipient?`mailto:${recipient}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(message)}`:"";if(input.kind==="phone")return recipient?`tel:${recipient}`:"";if(input.kind==="sms")return recipient?`SMSTO:${recipient}:${message}`:"";if(input.kind==="whatsapp"){const phone=recipient.replace(/\D/g,"");return phone?`https://wa.me/${phone}${message?`?text=${encodeURIComponent(message)}`:""}`:""}const name=input.contactName?.trim()??"",email=input.contactEmail?.trim()??"",phone=input.contactPhone?.trim()??"";return name||email||phone?`MECARD:N:${escapeContact(name)};EMAIL:${escapeContact(email)};TEL:${escapeContact(phone)};;`:""}
const luminance=(hex:string)=>{const channels=[1,3,5].map(index=>parseInt(hex.slice(index,index+2),16)/255).map(value=>value<=.04045?value/12.92:((value+.055)/1.055)**2.4);return .2126*channels[0]+.7152*channels[1]+.0722*channels[2]};
export function qrContrastRatio(a:string,b:string){const first=luminance(a),second=luminance(b);return (Math.max(first,second)+.05)/(Math.min(first,second)+.05)}
