import assert from "node:assert/strict";
import {readFileSync,readdirSync} from "node:fs";
import ts from "typescript";

function load(path){const source=readFileSync(path,"utf8"),compiled=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,module={exports:{}};new Function("require","module","exports",compiled)(require=>{throw new Error(`Unexpected import: ${require}`)},module,module.exports);return module.exports}
const {labTools,labCategoryOrder}=load("data/lab-tools.ts");
const expected=["qr-code-generator","image-compressor","image-resizer","image-format-converter","image-cropper","pdf-merger","pdf-compressor","random-picker"];
for(const slug of expected)assert.ok(labTools.some(tool=>tool.slug===slug),slug);
const newToolPages=expected.map(slug=>({slug,source:readFileSync(`app/lab/${slug}/page.tsx`,"utf8")}));
const seoRecords=newToolPages.map(({slug,source})=>{const match=source.match(/createToolPageMetadata\(\{title:"([^"]+)",description:"([^"]+)",path:"([^"]+)"\}\)/);assert.ok(match,`${slug} needs explicit tool metadata`);assert.equal(match[3],`/lab/${slug}`,`${slug} needs a self canonical path`);assert.ok(match[1].length>=15,`${slug} needs a meaningful title`);assert.ok(match[2].length>=60,`${slug} needs a meaningful description`);assert.match(source,/ToolPageLayout title="[^"]+" description="[^"]+" path="\/lab\//);return {title:match[1],description:match[2],path:match[3]}});
assert.equal(new Set(seoRecords.map(record=>record.title)).size,expected.length,"new tool titles must be unique");
assert.equal(new Set(seoRecords.map(record=>record.description)).size,expected.length,"new tool descriptions must be unique");
assert.equal(new Set(seoRecords.map(record=>record.path)).size,expected.length,"new tool canonicals must be unique");
const toolLayoutSource=readFileSync("components/lab/tool-page-layout.tsx","utf8");
for(const contract of ["<h1>{title}</h1>","webApplicationStructuredData","<JsonLd data={schema}","getToolEducation","href=\"/lab\""])assert.ok(toolLayoutSource.includes(contract),contract);
const sitemapSource=readFileSync("app/sitemap.ts","utf8");assert.match(sitemapSource,/\.\.\.labTools\.map\(tool=>entry\(`\/lab\/\$\{tool\.slug\}`/);
const labDirectorySource=readFileSync("components/lab/lab-directory.tsx","utf8");assert.match(labDirectorySource,/tools\.map|categoryTools\.map/);
assert.match(labDirectorySource,/id="lab-tool-directory"/);
assert.deepEqual(labCategoryOrder,["Website & SEO","Images","Documents","Developer & Design","Everyday"]);
assert.equal(new Set(labTools.map(tool=>tool.slug)).size,labTools.length);
assert.ok(labTools.every(tool=>tool.documentationSlug&&tool.searchTerms.length>=4));

const normalize=value=>value.toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const match=query=>{const terms=normalize(query).split(" ");return labTools.find(tool=>{const text=normalize([tool.title,tool.description,tool.category,...tool.searchTerms].join(" "));return terms.every(term=>text.includes(term))})?.slug};
for(const [query,slug] of [["make photo smaller","image-compressor"],["reduce photo file size","image-compressor"],["resize picture","image-resizer"],["change png to webp","image-format-converter"],["join pdf","pdf-merger"],["combine pdf files","pdf-merger"],["make pdf smaller","pdf-compressor"],["make qr","qr-code-generator"],["choose random name","random-picker"],["choose randomly","random-picker"]])assert.equal(match(query),slug,query);

const localSources=["components/lab/image-tool.tsx","components/lab/pdf-tool.tsx","components/lab/qr-code-tool.tsx","components/lab/random-picker-tool.tsx"].map(path=>readFileSync(path,"utf8")).join("\n");
const fileValidation=readFileSync("lib/lab/file-validation.ts","utf8");
assert.match(fileValidation,/PNG/);assert.match(fileValidation,/RIFF/);assert.match(fileValidation,/WEBP/);assert.match(fileValidation,/%PDF-/);
assert.match(fileValidation,/createImageBitmap/);assert.match(fileValidation,/file\.slice\(0,32\)/);assert.match(fileValidation,/file\.slice\(0,5\)/);
const imageProcessorMemory=readFileSync("lib/lab/process-image.ts","utf8");
assert.match(imageProcessorMemory,/canvas\.width=0;canvas\.height=0/);
assert.match(imageProcessorMemory,/canvas\.width=1;canvas\.height=1/);
assert.match(imageProcessorMemory,/decoded\.close\(\)/);
assert.match(fileValidation,/image\.src="";URL\.revokeObjectURL/);
assert.doesNotMatch(localSources,/fetch\(|XMLHttpRequest|axios|\/api\//);
const localToolRoutes=expected.map(slug=>readFileSync(`app/lab/${slug}/page.tsx`,"utf8")).join("\n");
assert.doesNotMatch(localToolRoutes,/\/api\/|FormData|server action|use server/i);
const apiRoutes=readdirSync("app/api",{recursive:true}).map(String).join("\n");
for(const slug of expected)assert.doesNotMatch(apiRoutes,new RegExp(slug),`${slug} must not gain an upload API`);
const productionDependencies=Object.keys(JSON.parse(readFileSync("package.json","utf8")).dependencies??{}).join("\n");
assert.doesNotMatch(productionDependencies,/@aws-sdk|\bs3\b|firebase|supabase|prisma/i);
const pdfToolSource=readFileSync("components/lab/pdf-tool.tsx","utf8");
assert.match(pdfToolSource,/useObjectStreams:true/);
assert.match(pdfToolSource,/savePdfHandoff/);
assert.match(pdfToolSource,/Add PDF files/);
assert.match(pdfToolSource,/getPageCount\(\)/);
assert.match(pdfToolSource,/draggable=\{mode==="merge"\}/);
assert.match(pdfToolSource,/onDragStart/);
assert.match(pdfToolSource,/moveTo\(from,index\)/);
assert.match(pdfToolSource,/await import\("pdf-lib"\)/);
assert.doesNotMatch(pdfToolSource,/from\s+["']pdf-lib["']/);
assert.doesNotMatch(pdfToolSource,/fetch\(|XMLHttpRequest|axios|\/api\//);
for(const mergeResult of ["Merged PDF ready","Filename","Download merged PDF","Need a smaller file?","Compress this PDF →"])assert.match(pdfToolSource,new RegExp(mergeResult.replace("?","\\?")));
assert.match(pdfToolSource,/safePdfName\(downloadName\)/);
for(const pdfFailure of ["password protected","appears to be damaged","has no pages","too large to process safely","ran out of memory","not a supported PDF"])assert.match(pdfToolSource,new RegExp(pdfFailure));
assert.match(pdfToolSource,/catch\(failure\)\{setError\(pdfFailureMessage\(failure\)\)\}/);
assert.doesNotMatch(pdfToolSource,/setError\([^)]*failure\.message/);
for(const compressionFlow of ["Select goal","Smallest file","Balanced","Best quality","Compress PDF"])assert.match(pdfToolSource,new RegExp(compressionFlow));
assert.match(pdfToolSource,/compressionGoal==="smallest"\|\|saving>=\.02/);
assert.match(pdfToolSource,/compressionGoal!=="best-quality"/);
assert.match(pdfToolSource,/original PDF bytes unchanged/);
const simpleToolStyles=readFileSync("components/lab/simple-tools.module.css","utf8");
for(const pdfAction of ["Drag files to change their order.","Move ","Remove "])assert.match(pdfToolSource,new RegExp(pdfAction.replace(".","\\.")));
const pdfHandoff=readFileSync("lib/lab/pdf-handoff.ts","utf8");
assert.match(pdfHandoff,/indexedDB\.open/);
assert.match(pdfHandoff,/store\.delete\(RECORD_KEY\)/);
assert.match(pdfHandoff,/export async function clearPdfHandoff/);
assert.match(pdfToolSource,/clearPdfHandoff\(\)/);
assert.doesNotMatch(pdfHandoff,/fetch\(|XMLHttpRequest|localStorage/);
assert.match(readFileSync("components/lab/qr-code-tool.tsx","utf8"),/await import\("qrcode"\)/);
const qrCore=readFileSync("lib/lab/qr-core.ts","utf8");
for(const qrType of ["website","text","wifi","email","phone","sms","whatsapp","contact"])assert.match(readFileSync("components/lab/qr-code-tool.tsx","utf8"),new RegExp(`value=\\"${qrType}\\"`));
assert.match(qrCore,/https:\/\//);
assert.match(readFileSync("components/lab/qr-code-tool.tsx","utf8"),/Encoded text/);
assert.match(qrCore,/WIFI:T:/);
assert.match(readFileSync("components/lab/qr-code-tool.tsx","utf8"),/Copy encoded text/);
assert.match(readFileSync("components/lab/qr-code-tool.tsx","utf8"),/window\.print\(\)/);
assert.match(readFileSync("components/lab/simple-tools.module.css","utf8"),/Best for sharing and everyday use/);
assert.match(readFileSync("components/lab/simple-tools.module.css","utf8"),/Best for printing at any size/);
assert.match(readFileSync("components/lab/qr-code-tool.tsx","utf8"),/This colour combination may be difficult to scan/);
assert.match(readFileSync("components/lab/qr-code-tool.tsx","utf8"),/Quiet zone/);
assert.match(readFileSync("components/lab/qr-code-tool.tsx","utf8"),/<summary>Customise<\/summary>/);
assert.match(readFileSync("components/lab/qr-code-tool.tsx","utf8"),/errorCorrectionLevel/);
assert.match(readFileSync("app/lab/qr-code-generator/page.tsx","utf8"),/QR image itself does not expire/);
assert.match(readFileSync("app/lab/qr-code-generator/page.tsx","utf8"),/does not create an editable destination, scan analytics or a tracking redirect/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/await import\("@\/lib\/lab\/process-image"\)/);
const imageProcessor=readFileSync("lib/lab/process-image.ts","utf8");
const toolErrors=readFileSync("lib/lab/tool-errors.ts","utf8");
const imageWorker=readFileSync("lib/lab/image-processing.worker.ts","utf8");
assert.match(imageProcessor,/createImageBitmap/);
assert.match(imageProcessor,/imageOrientation:"from-image"/);
assert.match(imageProcessor,/image\.naturalWidth/);
assert.match(imageProcessor,/image\.naturalHeight/);
assert.match(imageProcessor,/URL\.revokeObjectURL/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/may not keep camera, location or other embedded metadata/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/reduce unintended personal information/);
assert.match(imageProcessor,/OffscreenCanvas/);
assert.match(imageProcessor,/convertToBlob/);
assert.match(imageProcessor,/canvas\.toBlob/);
assert.match(imageProcessor,/new Worker\(new URL\("\.\/image-processing\.worker\.ts",import\.meta\.url\),\{type:"module"\}\)/);
assert.match(imageProcessor,/worker\.terminate\(\)/);
assert.match(imageWorker,/createImageBitmap/);
assert.match(imageWorker,/OffscreenCanvas/);
assert.match(imageWorker,/decoded\.close\(\)/);
assert.doesNotMatch(imageWorker,/requestAnimationFrame|setInterval|setState/);
assert.match(readFileSync("docs/PDF_COMPRESSION_WASM_EVALUATION.md","utf8"),/must not receive frame-by-frame progress events/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/addEventListener\("paste"/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/multiple=\{mode==="compress"\}/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Total original/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Total output/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/downloadBatchItem/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/status:"queued"\|"processing"\|"done"\|"error"/);
assert.doesNotMatch(productionDependencies,/jszip|fflate|archiver/i);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/clipboardData/);
for(const preset of ["Smaller file","Balanced","Keep quality"])assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),new RegExp(preset));
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Recommended/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Download compressed image/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/savedPercent/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Keep proportions/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Current size/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Custom size/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/placeholder=\{keepProportions\?`Auto \(\$\{height\}px\)`/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/setHeight\(Math\.round\(next\*sourceHeight\/sourceWidth\)\)/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/useState\(true\)/);
for(const resizeChoice of ["Pixels","Percentage","50% smaller","25% smaller","Square","Landscape","Portrait","HD","Full HD"])assert.match(readFileSync("components/lab/image-tool.tsx","utf8")+readFileSync("data/image-resize-presets.ts","utf8"),new RegExp(resizeChoice));
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/sourceWidth\*percentage\/100/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/not official platform requirements/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Do not enlarge smaller images/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/setPreventUpscaling\(true\)/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Math\.min\(1,sourceWidth\/width,sourceHeight\/height\)/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/cannot create missing detail/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/result may look softer/);
for(const resizeResultText of ["Before","After","File size","Download resized image"])assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),new RegExp(resizeResultText));
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/sourceWidth\} × \{sourceHeight/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/result\.width\} × \{result\.height/);
for(const format of ["JPEG","PNG","WebP"])assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),new RegExp(`>${format}<`));
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/toDataURL\("image\/avif"\)/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/avifOutputSupported&&<option value="image\/avif">AVIF/);
assert.doesNotMatch(readFileSync("components/lab/image-tool.tsx","utf8"),/HEIC/);
for(const intent of ["What do you need it for?","Website","Smaller file","Keep transparency","Choose format myself","Recommended"])assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),new RegExp(intent.replace("?","\\?")));
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/if\(intent==="transparency"\)setFormat\("image\/png"\)/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/image is not converted until/);
for(const explanation of ["Good for photographs","No transparent background","Good for graphics and transparency","Often larger","Good general web format","Supports transparency and is often smaller"])assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),new RegExp(explanation));
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/convertIntent==="manual"&&<dl/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/compareImageFormats/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Real file-size comparison/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Smallest/);
assert.match(readFileSync("lib/lab/process-image.ts","utf8"),/blob&&blob\.size>0&&blob\.type===type/);
assert.match(readFileSync("lib/lab/process-image.ts","utf8"),/Promise\.all\(outputTypes\.map/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Position the crop/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Drag the outlined area/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/onPointerMove/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/setPointerCapture/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/role="slider"/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/ArrowLeft/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Horizontal position \(%\)/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Vertical position \(%\)/);
assert.match(readFileSync("components/lab/pdf-tool.tsx","utf8"),/moved to position/);
for(const cropControl of ["Free","Square 1:1","Landscape 16:9","Portrait 4:5","Story 9:16","Selection width","Selection height","Zoom","Rotate 90°","Reset crop"])assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),new RegExp(cropControl));
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/not official social-platform requirements/);
assert.match(readFileSync("lib/lab/process-image.ts","utf8"),/cropRotation\*Math\.PI\/180/);
assert.match(readFileSync("lib/lab/process-image.ts","utf8"),/scale\(cropZoom,cropZoom\)/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/mode==="crop"\?<dl className=\{styles\.cropResult\}/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/<dt>Original<\/dt><dd>\{sourceWidth\} × \{sourceHeight\}/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/<dt>Crop<\/dt><dd>\{result\.width\} × \{result\.height\}/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Download cropped image/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Before and after/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Original image before compression/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/No smaller version was created/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/Keeping the original may be better/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/saveImageHandoff/);
const imageHandoff=readFileSync("lib/lab/image-handoff.ts","utf8");
assert.match(imageHandoff,/indexedDB\.open/);
assert.match(imageHandoff,/10\*60\*1000/);
assert.match(imageHandoff,/store\.delete\(RECORD_KEY\)/);
assert.match(imageHandoff,/export async function clearImageHandoff/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/clearImageHandoff\(\)/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/result\.width\}x\$\{result\.height/);
assert.doesNotMatch(imageHandoff,/fetch\(|XMLHttpRequest|localStorage/);
const randomPickerSource=readFileSync("components/lab/random-picker-tool.tsx","utf8");
const randomCore=readFileSync("lib/lab/random-core.ts","utf8");
assert.match(randomCore,/crypto\.getRandomValues/);
assert.match(randomCore,/UINT32_RANGE-\(UINT32_RANGE%length\)/);
assert.match(randomCore,/while\(values\[0\]>=limit\)/);
assert.match(randomCore,/unbiasedRandomIndex\(index\+1/);
assert.match(randomPickerSource,/Remember this list/);
assert.match(randomPickerSource,/if\(rememberList\)localStorage\.setItem/);
assert.match(randomPickerSource,/else localStorage\.removeItem/);
assert.doesNotMatch(randomPickerSource,/fetch\(|XMLHttpRequest/);
assert.match(readFileSync("data/writing.ts","utf8"),/not an audited lottery or regulated drawing system/);
assert.match(readFileSync("components/lab/simple-tools.module.css","utf8"),/Private by default/);
assert.match(readFileSync("components/lab/svg-base64-tool.tsx","utf8"),/Your SVG is processed locally in your browser and is not uploaded to our server\./);
const sharedLayout=readFileSync("components/lab/tool-page-layout.tsx","utf8");
for(const workflowStage of ["Input","Process","Result","Continue"])assert.match(sharedLayout,new RegExp(`>${workflowStage}<`));
assert.match(sharedLayout,/aria-label="Tool workflow"/);
for(const stage of ["Tool","Next useful actions","Related tools"])assert.match(sharedLayout,new RegExp(stage));
assert.match(sharedLayout,/advertisement\?:ReactNode/);
assert.ok(sharedLayout.indexOf("{children}")<sharedLayout.indexOf("!tool.advertisingEligible&&advertisement"),"tool must render before the optional advertisement position");
const toolAds=readFileSync("components/lab/tool-advertisement.tsx","utf8");
assert.match(toolAds,/placement!=="after-tool-result"/);
assert.match(toolAds,/querySelector\("\.resultHero"\)/);
assert.match(toolAds,/data-tool-processing/);
assert.match(toolAds,/MutationObserver/);
assert.match(toolAds,/className="tool-ad-boundary"/);
const globalCss=readFileSync("app/globals.css","utf8");
assert.match(globalCss,/\.tool-ad-boundary\{[^}]*margin-block:clamp\(6rem/);
assert.match(globalCss,/\.advertisement \{[^}]*position:static!important; inset:auto!important;/);
assert.match(globalCss,/\.adsense-inventory\{position:static!important;/);
assert.match(globalCss,/\.advertisement[^}]*animation:none!important/);
assert.match(globalCss,/--ad-reserved-size:clamp\(9rem,18vw,12rem\)/);
assert.match(globalCss,/min-block-size:var\(--ad-reserved-size\); max-block-size:var\(--ad-reserved-size\)/);
assert.match(globalCss,/contain:size layout paint/);
assert.match(readFileSync("components/ui/advertisement.tsx","utf8"),/IntersectionObserver/);
assert.match(readFileSync("components/ui/advertisement.tsx","utf8"),/consent==="accepted"/);
assert.match(readFileSync("components/ui/advertisement.tsx","utf8"),/publisherContent\.textContent\.trim\(\)\.length<20/);
assert.doesNotMatch(readFileSync("app/layout.tsx","utf8"),/AdProvider|AdSlot|Advertisement/);
const adProvider=readFileSync("components/ads/AdProvider.tsx","utf8"),adSlot=readFileSync("components/ads/AdSlot.tsx","utf8"),adConfig=readFileSync("lib/advertising/config.ts","utf8"),exampleEnv=readFileSync(".env.example","utf8");
assert.match(exampleEnv,/NEXT_PUBLIC_ADSENSE_ENABLED=false/);
assert.match(exampleEnv,/NEXT_PUBLIC_ADSENSE_CLIENT=\s*(?:\r?\n|$)/);
assert.match(adConfig,/NEXT_PUBLIC_ADSENSE_ENABLED==="true"/);
assert.match(adConfig,/\^ca-pub-/);
assert.match(adProvider,/consent!=="accepted"/);
assert.match(adProvider,/personalizationConsent==="accepted"\|\|personalizationConsent==="rejected"/);
assert.match(adProvider,/strategy="lazyOnload"/);
assert.match(adSlot,/adsbygoogle/);
const labIndexAd=readFileSync("components/ads/LabIndexAdvertisement.tsx","utf8"),labPage=readFileSync("app/lab/page.tsx","utf8");
assert.match(labIndexAd,/placement="after-lab-directory"/);
assert.match(labIndexAd,/querySelector\("\.lab-category article"\)/);
assert.ok(labPage.indexOf("<LabDirectory")<labPage.indexOf("<LabIndexAdvertisement"),"Lab ad must follow the complete searchable directory");
assert.equal((labPage.match(/<LabIndexAdvertisement/g)??[]).length,1,"Lab index may contain only one ad placement");
const writingDetail=readFileSync("app/writing/[slug]/page.tsx","utf8"),documentationAd=readFileSync("components/ads/DocumentationAdvertisement.tsx","utf8");
assert.match(writingDetail,/index===2&&article\.sections\.length>=5/);
assert.equal((writingDetail.match(/<DocumentationAdvertisement/g)??[]).length,1,"Lab notes may contain only one ad placement");
assert.match(documentationAd,/placement="between-documentation-sections"/);
assert.ok(writingDetail.indexOf("<section id={sectionId}")<writingDetail.indexOf("<DocumentationAdvertisement"),"documentation ad must follow a complete section");
assert.doesNotMatch(documentationAd,/<pre|<code|dangerouslySetInnerHTML/);
const productEvents=readFileSync("lib/analytics/product-events.ts","utf8"),toolOpened=readFileSync("components/analytics/tool-opened-event.tsx","utf8");
for(const event of ["tool_opened","qr_generated","qr_downloaded","image_compressed","image_downloaded","image_handoff_clicked","image_resized","image_converted","image_cropped","pdf_merged","pdf_compressed","random_pick_completed"])assert.match(productEvents,new RegExp(`${event}:`),event);
assert.match(toolOpened,/trackProductEvent\("tool_opened",\{tool_name:toolName\}\)/);
for(const [source,event] of [[readFileSync("components/lab/qr-code-tool.tsx","utf8"),"qr_generated"],[readFileSync("components/lab/image-tool.tsx","utf8"),"image_compressed"],[readFileSync("components/lab/pdf-tool.tsx","utf8"),"pdf_merged"],[readFileSync("components/lab/random-picker-tool.tsx","utf8"),"random_pick_completed"]])assert.match(source,new RegExp(`trackProductEvent\\("${event}"`),event);
const analyticsCalls=[productEvents,toolOpened,localSources].join("\n");
assert.doesNotMatch(analyticsCalls,/trackProductEvent\([^\n]*(?:filename|file_name|qr_content|wifi_password|email|image_data|pdf_content|picker_entries|personal_text)/i);
assert.doesNotMatch(productEvents,/\b(?:filename|qr_content|wifi_password|email|image|pdf_contents|random_picker_entries|personal_text)\s*:/i);
const homepagePerformanceBoundary=[readFileSync("app/page.tsx","utf8"),readFileSync("app/layout.tsx","utf8"),readFileSync("components/sections/home-page.tsx","utf8"),readFileSync("components/interactions/hero-stage.tsx","utf8")].join("\n");
assert.doesNotMatch(homepagePerformanceBoundary,/pdf-lib|qrcode|process-image|ImageTool|PdfTool|QrCodeTool|image-cropper|ghostscript|\.wasm/i);
assert.match(readFileSync("components/lab/pdf-tool.tsx","utf8"),/import\("pdf-lib"\)/);
assert.doesNotMatch(readFileSync("components/lab/pdf-tool.tsx","utf8"),/from\s+["']pdf-lib["']/);
assert.match(readFileSync("components/lab/qr-code-tool.tsx","utf8"),/import\("qrcode"\)/);
assert.doesNotMatch(readFileSync("components/lab/qr-code-tool.tsx","utf8"),/from\s+["']qrcode["']/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/await import\("@\/lib\/lab\/process-image"\)/);
assert.match(readFileSync("components/lab/image-tool.tsx","utf8"),/setError\(imageToolError\(caught\)\)/);
assert.match(toolErrors,/Your original file has not been changed/);
assert.match(toolErrors,/Try JPG, PNG or WebP instead/);
assert.doesNotMatch(readFileSync("components/lab/image-tool.tsx","utf8"),/setError\([^\n]*(?:caught|failure)\.(?:message|name)/);
assert.doesNotMatch(readFileSync("components/lab/svg-base64-tool.tsx","utf8"),/setError\([^\n]*(?:cause|failure)\.(?:message|name)/);
assert.doesNotMatch(productionDependencies,/ghostscript|gs-wasm|@jspawn\/jspawn|pdf-compressor-wasm/i);
const cmpSource=readFileSync("lib/advertising/cmp.ts","utf8");
assert.match(cmpSource,/certification:"google-certified-cmp"/);
assert.match(cmpSource,/getPersonalizationConsent\(\):AdvertisingConsent/);
assert.match(cmpSource,/does not infer or manufacture those signals/);
assert.doesNotMatch([adProvider,adSlot,toolAds].join("\n"),/Support me by clicking|Click our sponsors|Help us by visiting/i);
assert.equal(labTools.filter(tool=>tool.advertisingEligible).length,8);
assert.ok(sharedLayout.indexOf("after-tool-result")>sharedLayout.indexOf("{children}"));
assert.ok(sharedLayout.indexOf("after-tool-documentation")>sharedLayout.indexOf("tool-education"));
assert.doesNotMatch(localSources,/Advertisement|AdSlot|adsbygoogle/,"interactive tool implementations must not contain advertising inventory");
for(const source of [readFileSync("components/lab/image-tool.tsx","utf8"),readFileSync("components/lab/pdf-tool.tsx","utf8"),readFileSync("components/lab/qr-code-tool.tsx","utf8")])assert.match(source,/data-tool-processing=/);
console.log("✓ 8 new Lab tools, categories, natural-language aliases and local-processing boundaries passed.");
