import Image from "next/image";
import { PageIntro } from "@/components/ui/page-intro";
import { ExperienceList } from "@/components/sections/experience-list";
import { education } from "@/data/experience";
import { skills } from "@/data/skills";
import { createPageMetadata } from "@/lib/seo/metadata";

export const metadata=createPageMetadata({title:"About Pujan Chapagain",description:"Learn about Pujan Chapagain’s frontend practice, professional experience, MSc education and technical skills in Glasgow.",path:"/about"});
export default function AboutPage(){return <main id="main"><PageIntro index="01" eyebrow="About" title="A frontend practice built on curiosity." description="Design sensitivity and engineering discipline, brought together to make useful digital experiences." /><section className="about-page section"><div className="about-grid"><div className="portrait portrait-flat"><Image src="/pujan-chapagain-portrait.png" alt="Pujan Chapagain wearing a suit and sunglasses" width={660} height={499} sizes="(max-width: 760px) 100vw, 40vw" priority /></div><div className="prose"><h2>Clarity before decoration.</h2><p>I’m Pujan Chapagain, a frontend developer based in Glasgow, Scotland. I’m passionate about creating intuitive design solutions that enhance people’s experience while meeting real needs.</p><p>My work is driven by a simple goal: craft delightful experiences through user-centred research, streamlined workflows, and open-minded iterative collaboration. I care about the relationship between visual direction and implementation—the point where a strong concept becomes reliable software.</p></div></div></section><section className="section"><div className="section-head"><p className="eyebrow">Experience</p><h2>The working<br />timeline.</h2></div><ExperienceList /><div className="skill-grid">{Object.entries(skills).map(([group,items])=><div key={group}><h3>{group}</h3><p>{items.join(" · ")}</p></div>)}</div></section><section className="section education"><p className="eyebrow">Education</p>{education.map(item=><p key={item.course}><strong>{item.course}</strong> — {item.school}, {item.place}{item.year&&<> · {item.year}</>}</p>)}</section></main>;}
