import Link from "next/link";
import { LegalReviewNote } from "@/components/ui/legal-review-note";
import { PageIntro } from "@/components/ui/page-intro";
import { createPageMetadata } from "@/lib/seo/metadata";

export const metadata=createPageMetadata({title:"Privacy Notice",description:"Learn how this portfolio handles contact messages, submitted URLs, temporary reports, browser storage, security processing and third-party services.",path:"/privacy"});

export default function PrivacyPage(){return <main id="main">
  <PageIntro index="06" eyebrow="Privacy" title="Privacy, stated plainly." description="This page describes the current application behaviour and identifies deployment details that still need confirmation before publication." />
  <article className="privacy-body">
    <LegalReviewNote>Confirm the site owner or controller identity, postal contact details, hosting provider, server-log retention, lawful bases, international transfers and the effective date with a qualified adviser before treating this as a final privacy notice.</LegalReviewNote>
    <section><p className="eyebrow">SUBMITTED URLS</p><h2>Public pages requested for diagnosis.</h2><p>When you submit a URL, Web Doctor sends it to this site&apos;s server. The server requests the public page and a small number of public SEO resources, such as robots.txt and a likely sitemap, then returns a structured report.</p><p>The requested website can record Web Doctor&apos;s request under its own policies. No account, email address or user API key is required.</p></section>
    <section><p className="eyebrow">CONTACT MESSAGES</p><h2>Email delivery, not public chat.</h2><p>When you choose Send, the contact form submits your email address, selected topic and message to this site&apos;s server. They are used to deliver the enquiry and allow a reply to the address you supplied. No account is required, and the site does not create or publish a chat history.</p><p>Resend is used as the email delivery provider. The server passes the sender configuration, destination inbox, validated reply address, topic and message content to Resend so the email can be delivered. An unfinished draft containing only your email, topic and message can remain in sessionStorage on your device until it is sent, cleared or the browser session ends. A successfully submitted draft is removed from sessionStorage.</p><p>The form uses validation, a hidden honeypot, short-lived rate limiting and an opaque request identifier for spam prevention, duplicate protection and service security. Delivery-failure logs contain the request identifier and controlled error category rather than the submitted email or message.</p><p>Cloudflare Turnstile is not currently enabled. If it is enabled, a verification token will be sent to this server and checked with Cloudflare as part of spam prevention; Cloudflare may process associated technical request information under its own terms and privacy materials.</p><LegalReviewNote>Before production publication, confirm Resend and any enabled Turnstile processing, provider roles, retention, locations, transfer safeguards, lawful basis and required notices with a qualified adviser.</LegalReviewNote></section>
    <section><p className="eyebrow">TEMPORARY CACHING</p><h2>Reports are cached briefly.</h2><p>Completed structured reports are currently held in application memory for approximately ten minutes to reduce duplicate requests. Downloaded HTML and manually pasted HTML are processed for the diagnosis and are not included in that report cache or intentionally stored permanently by the application.</p><p>Short-lived in-memory request counters provide best-effort abuse protection within one running application instance. Production hosting or network infrastructure may apply additional shared request limits.</p></section>
    <section><p className="eyebrow">SERVER LOGS</p><h2>Infrastructure may create technical logs.</h2><p>The application code does not create a customer profile from submitted URLs. Hosting and network providers may nevertheless record ordinary request details such as IP address, time, requested route, browser information and response status for security and service operation.</p><LegalReviewNote>Identify the production hosting and network providers, exactly what they log, retention periods, access controls and deletion processes.</LegalReviewNote></section>
    <section><p className="eyebrow">ON YOUR DEVICE</p><h2>Recent checks and contact drafts use browser storage.</h2><p>Web Doctor stores analysed URLs, scores and check dates in localStorage. The contact form can store an unfinished email address, topic and message in sessionStorage. These values remain on that device and are not silently uploaded as separate history features. Browser controls can clear either storage area.</p></section>
    <section><p className="eyebrow">ANALYTICS</p><h2>No analytics integration is currently installed.</h2><p>The current application does not include an analytics SDK or tracking tag. If analytics is introduced, this notice and the <Link href="/cookies">Cookies page</Link> must be updated before deployment, including the provider, data collected, purpose, retention and consent behaviour.</p></section>
    <section><p className="eyebrow">ADVERTISING</p><h2>Advertising is not currently enabled.</h2><p>No AdSense or advertising network code is currently loaded. The application is designed to keep future ads disabled unless a certified consent-management platform reports the required advertising consent. Enabling advertising will require updated disclosures covering the provider, cookies or storage, personalisation settings and choices available to visitors.</p></section>
    <section><p className="eyebrow">COOKIES</p><h2>No intentional application cookies today.</h2><p>The application currently uses localStorage and sessionStorage rather than application cookies. Deployment infrastructure may set essential security or delivery cookies; this must be verified against the live hosting configuration. See the <Link href="/cookies">Cookies page</Link> for the current inventory and review notes.</p></section>
    <section><p className="eyebrow">THIRD PARTIES</p><h2>Only necessary service relationships should be listed.</h2><p>Current requests can involve the production hosting and network providers, Resend for contact-email delivery and the public website submitted for analysis. Turnstile would add Cloudflare only if it is enabled. Links to external social profiles and project websites take you to services operating under their own notices.</p><LegalReviewNote>Confirm the production vendors, purposes, locations, contractual roles and transfer safeguards. Add analytics, advertising and CMP providers only if they are actually enabled.</LegalReviewNote></section>
    <section><p className="eyebrow">YOUR QUESTIONS</p><h2>Contact the site owner.</h2><p>For privacy questions, use the details on the <Link href="/contact">Contact page</Link>. Statutory rights and complaint information depend on the final controller and deployment details and must be reviewed before publication.</p></section>
  </article>
</main>;}
