import Link from "next/link";
import { AnimatedLogo } from "./animated-logo";

const primaryLinks=[{href:"/work",label:"Work"},{href:"/about",label:"About"},{href:"/lab",label:"Lab"},{href:"/writing",label:"Writing"},{href:"/contact",label:"Contact"}];
const commandLinks=[{href:"/",label:"Home",group:"Portfolio"},...primaryLinks.map(link=>({...link,group:"Portfolio"})),{href:"/lab/web-doctor",label:"Web Doctor",group:"Free tools"},{href:"/lab/meta-generator",label:"Meta Tag Generator",group:"Free tools"},{href:"/lab/contrast-checker",label:"Contrast Checker",group:"Free tools"},{href:"/lab/clamp-generator",label:"CSS Clamp Generator",group:"Free tools"},{href:"/lab/open-graph-preview",label:"Open Graph Preview",group:"Free tools"}];

const navigationScript=`(()=>{const header=document.querySelector('[data-site-header]');const dialog=document.querySelector('[data-command-dialog]');const trigger=document.querySelector('[data-command-trigger]');const close=document.querySelector('[data-command-close]');const input=document.querySelector('[data-command-input]');const empty=document.querySelector('[data-command-empty]');if(!(header instanceof HTMLElement)||!(dialog instanceof HTMLDialogElement)||!(trigger instanceof HTMLButtonElement)||!(close instanceof HTMLButtonElement)||!(input instanceof HTMLInputElement))return;let frame=0;const compact=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>header.toggleAttribute('data-compact',scrollY>48))};const open=()=>{if(dialog.open)return;input.value='';dialog.querySelectorAll('[data-command-link]').forEach(link=>link.removeAttribute('hidden'));empty?.setAttribute('hidden','');dialog.showModal();requestAnimationFrame(()=>input.focus())};const shut=()=>{dialog.close();trigger.focus()};addEventListener('scroll',compact,{passive:true});addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();open()}});trigger.addEventListener('click',open);close.addEventListener('click',shut);dialog.addEventListener('click',event=>{if(event.target===dialog)shut()});input.addEventListener('input',()=>{const query=input.value.trim().toLowerCase();let visible=0;dialog.querySelectorAll('[data-command-link]').forEach(link=>{const match=(link.textContent||'').toLowerCase().includes(query);link.toggleAttribute('hidden',!match);if(match)visible++});empty?.toggleAttribute('hidden',visible>0)});compact()})();`;

export function SiteNavigation(){return <><header className="site-header" data-site-header><Link className="wordmark" href="/" aria-label="Pujan Chapagain, home"><AnimatedLogo /><small>Frontend developer<br />Glasgow, Scotland</small></Link><nav aria-label="Primary navigation">{primaryLinks.map(link=><Link key={link.href} href={link.href}>{link.label}</Link>)}</nav><div className="site-actions"><Link className="availability" href="/contact"><i aria-hidden="true" /> Available for select work</Link><button className="command-trigger" type="button" data-command-trigger aria-haspopup="dialog">Search <kbd>⌘K</kbd></button></div></header><dialog className="command-dialog" data-command-dialog aria-labelledby="command-heading"><div><header><div><span>COMMAND NAVIGATION</span><h2 id="command-heading">Where would you like to go?</h2></div><button type="button" data-command-close aria-label="Close command navigation">Esc</button></header><label htmlFor="command-search">Search pages and tools</label><input id="command-search" data-command-input placeholder="Type a page or tool…" autoComplete="off" /><nav aria-label="Command results">{commandLinks.map((link,index)=><Link href={link.href} data-command-link key={link.href}><span>{String(index+1).padStart(2,"0")}</span><strong>{link.label}</strong><small>{link.group}</small></Link>)}<p data-command-empty hidden>No matching page. Try “Lab” or “Web Doctor”.</p></nav></div></dialog><script dangerouslySetInnerHTML={{__html:navigationScript}} /></>}
