"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import styles from "./simple-tools.module.css";
import {savePdfHandoff,takePdfHandoff} from "@/lib/lab/pdf-handoff";
import {useMobileResultScroll} from "@/lib/lab/use-mobile-result-scroll";
import {FileDropZone} from "@/components/lab/file-drop-zone";
import {validatePdfSignature} from "@/lib/lab/file-validation";

type PdfMode="merge"|"compress";
type PdfCompressionGoal="smallest"|"balanced"|"best-quality";
type PdfBusyPhase="idle"|"preparing"|"processing";
type PdfResult={url:string;blob:Blob;size:number;pages:number;inputCount:number;inputSize:number;candidateSize?:number;usedOriginal?:boolean;compressionOutcome?:"compressed"|"minimal"|"larger"|"original"};
type PdfFailureCode="ENCRYPTED"|"CORRUPT"|"EMPTY"|"TOO_LARGE"|"MEMORY"|"UNSUPPORTED";
type MemoryAwareNavigator=Navigator&{deviceMemory?:number};
class PdfToolError extends Error{constructor(readonly code:PdfFailureCode){super(code)}}
const prettyBytes=(bytes:number)=>bytes<1048576?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1048576).toFixed(1)} MB`;
const fileKey=(file:File)=>`${file.name}:${file.size}:${file.lastModified}`;
const LARGE_PDF_MOBILE_BYTES=20*1024*1024;
const LARGE_PDF_DESKTOP_BYTES=35*1024*1024;
function needsLargePdfWarning(file:File){const navigatorMemory=(navigator as MemoryAwareNavigator).deviceMemory,constrainedDevice=(typeof navigatorMemory==="number"&&navigatorMemory<=4)||window.matchMedia("(max-width: 768px), (pointer: coarse)").matches;return file.size>(constrainedDevice?LARGE_PDF_MOBILE_BYTES:LARGE_PDF_DESKTOP_BYTES)}
let pdfRuntimePromise:ReturnType<typeof importPdfRuntime>|null=null;
async function importPdfRuntime(){return await import("pdf-lib")}
function loadPdfRuntime(){pdfRuntimePromise??=importPdfRuntime().catch(failure=>{pdfRuntimePromise=null;throw failure});return pdfRuntimePromise}
const safePdfName=(value:string)=>{const base=value.trim().replace(/\.pdf$/i,"").replace(/[\\/:*?"<>|\u0000-\u001f]/g,"-").replace(/\s+/g," ").slice(0,116).trim();return `${base||"merged-document"}.pdf`};
const pdfFailureMessage=(failure:unknown)=>{
  if(failure instanceof PdfToolError){const messages:Record<PdfFailureCode,string>={ENCRYPTED:"This PDF is password protected.\n\nRemove the password first, then try again.",CORRUPT:"This PDF appears to be damaged.\n\nTry opening and saving it again in a PDF reader, then retry.",EMPTY:"This PDF has no pages.\n\nRemove it and choose a PDF that contains at least one page.",TOO_LARGE:"This PDF is too large to process safely here.\n\nChoose a file smaller than 50 MB.",MEMORY:"This browser ran out of memory while processing the PDF.\n\nTry fewer or smaller files, then run the merge again.",UNSUPPORTED:"This file is not a supported PDF.\n\nChoose a standard .pdf file and try again."};return messages[failure.code]}
  const detail=failure instanceof Error?failure.message.toLowerCase():"";
  if(/encrypt|password/.test(detail))return pdfFailureMessage(new PdfToolError("ENCRYPTED"));
  if(failure instanceof RangeError||/memory|allocation|array buffer/.test(detail))return pdfFailureMessage(new PdfToolError("MEMORY"));
  if(/invalid|corrupt|parse|header|xref|catalog/.test(detail))return pdfFailureMessage(new PdfToolError("CORRUPT"));
  return "This PDF could not be processed.\n\nIt may be damaged or use an unsupported PDF feature.";
};

export function PdfTool({mode}:{mode:PdfMode}){
  const router=useRouter();
  const resultRef=useRef<HTMLElement>(null);
  const [files,setFiles]=useState<File[]>([]),[result,setResult]=useState<PdfResult|null>(null),[downloadName,setDownloadName]=useState(mode==="merge"?"merged-document.pdf":"compressed.pdf"),[pageCounts,setPageCounts]=useState<Record<string,number|null>>({}),[dragIndex,setDragIndex]=useState<number|null>(null),[busyPhase,setBusyPhase]=useState<PdfBusyPhase>("idle"),[handoffBusy,setHandoffBusy]=useState(false),[largeFileWarning,setLargeFileWarning]=useState(false),[largeFileConfirmed,setLargeFileConfirmed]=useState(false),[error,setError]=useState(""),[note,setNote]=useState("");
  const [compressionGoal,setCompressionGoal]=useState<PdfCompressionGoal>("balanced");
  useEffect(()=>()=>{if(result)URL.revokeObjectURL(result.url)},[result]);
  const readPageCounts=useCallback(async(incoming:File[])=>{const {PDFDocument}=await loadPdfRuntime();const entries=await Promise.all(incoming.map(async file=>{try{const document=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:false});return [fileKey(file),document.getPageCount()] as const}catch{return [fileKey(file),null] as const}}));setPageCounts(current=>({...current,...Object.fromEntries(entries)}))},[]);
  useEffect(()=>{if(mode!=="compress")return;let active=true;void takePdfHandoff().then(file=>{if(!active||!file)return;setFiles([file]);setLargeFileWarning(needsLargePdfWarning(file));setLargeFileConfirmed(false);void readPageCounts([file]);setDownloadName(`${file.name.replace(/\.pdf$/i,"")}-compressed.pdf`);setResult(null);setError("");setNote("Merged PDF received. Compress it when ready.")}).catch(()=>{});return()=>{active=false}},[mode,readPageCounts]);

  const add=async(incoming:FileList|File[])=>{const selected=Array.from(incoming),accepted:File[]=[];for(const file of selected){const signatureError=await validatePdfSignature(file);if(signatureError){setError(signatureError);continue}try{const {PDFDocument}=await loadPdfRuntime(),document=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:false});if(document.getPageCount()===0)throw new PdfToolError("EMPTY");accepted.push(file)}catch(failure){setError(pdfFailureMessage(failure))}}if(!accepted.length)return;const selectedForMode=mode==="compress"?[accepted[0]]:accepted;setLargeFileWarning(selectedForMode.some(needsLargePdfWarning));setLargeFileConfirmed(false);void readPageCounts(accepted);setFiles(current=>mode==="compress"?selectedForMode:[...current,...selectedForMode].slice(0,20));setResult(null);if(accepted.length===selected.length)setError("");setNote(accepted.length!==selected.length?"Unsupported or damaged files were skipped.":"")};
  const run=async()=>{if(mode==="merge"&&files.length<2){setError("Choose at least two PDFs to merge.");return}if(!files.length){setError("Choose a PDF first.");return}if(largeFileWarning&&!largeFileConfirmed){setError("This is a large PDF for browser processing. Confirm that you want to continue on this device first.");return}setBusyPhase("preparing");setError("");setNote("");try{const {PDFDocument}=await loadPdfRuntime();setBusyPhase("processing");let bytes:Uint8Array,pages=0,candidateSize:number|undefined,usedOriginal:boolean|undefined,compressionOutcome:PdfResult["compressionOutcome"];if(mode==="merge"){const output=await PDFDocument.create();for(const file of files){if(file.size>50*1024*1024)throw new PdfToolError("TOO_LARGE");const input=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:false});if(input.getPageCount()===0)throw new PdfToolError("EMPTY");const copied=await output.copyPages(input,input.getPageIndices());copied.forEach(page=>output.addPage(page))}pages=output.getPageCount();bytes=await output.save({useObjectStreams:true,addDefaultPage:false});setDownloadName("merged-document.pdf")}else{if(files[0].size>50*1024*1024)throw new PdfToolError("TOO_LARGE");const inputBytes=new Uint8Array(await files[0].arrayBuffer());const document=await PDFDocument.load(inputBytes,{ignoreEncryption:false,updateMetadata:false});pages=document.getPageCount();if(pages===0)throw new PdfToolError("EMPTY");const candidate=await document.save({useObjectStreams:true,addDefaultPage:false,objectsPerTick:50}),saving=(inputBytes.length-candidate.length)/inputBytes.length;candidateSize=candidate.length;const keepCandidate=compressionGoal!=="best-quality"&&candidate.length<inputBytes.length&&(compressionGoal==="smallest"||saving>=.02);usedOriginal=!keepCandidate;compressionOutcome=keepCandidate?"compressed":compressionGoal==="best-quality"?"original":candidate.length<inputBytes.length?"minimal":"larger";bytes=keepCandidate?candidate:inputBytes;setDownloadName(keepCandidate?`${files[0].name.replace(/\.pdf$/i,"")}-compressed.pdf`:files[0].name);setNote(compressionGoal==="best-quality"?"Best quality keeps the original PDF bytes unchanged.":keepCandidate?"The PDF structure was compacted.":candidate.length<inputBytes.length?`This PDF is already efficiently compressed. Only ${(saving*100).toFixed(1)}% could be saved, so the original was kept.`:"The compressed version is larger than your original. Keep the original file.")}const blob=new Blob([bytes as BlobPart],{type:"application/pdf"});if(result)URL.revokeObjectURL(result.url);setResult({url:URL.createObjectURL(blob),blob,size:blob.size,pages,inputCount:files.length,inputSize:files.reduce((total,file)=>total+file.size,0),candidateSize,usedOriginal,compressionOutcome})}catch(failure){setError(pdfFailureMessage(failure))}finally{setBusyPhase("idle")}};
  const move=(index:number,direction:-1|1)=>setFiles(current=>{const next=[...current],target=index+direction;if(target<0||target>=next.length)return current;[next[index],next[target]]=[next[target],next[index]];return next});
  const moveTo=(from:number,to:number)=>setFiles(current=>{if(from===to||from<0||to<0||from>=current.length||to>=current.length)return current;const next=[...current],[item]=next.splice(from,1);next.splice(to,0,item);return next});
  const clear=()=>{if(result)URL.revokeObjectURL(result.url);setFiles([]);setPageCounts({});setDragIndex(null);setResult(null);setDownloadName(mode==="merge"?"merged-document.pdf":"compressed.pdf");setCompressionGoal("balanced");setLargeFileWarning(false);setLargeFileConfirmed(false);setError("");setNote("")};
  const compressMerged=async()=>{if(!result)return;setHandoffBusy(true);setError("");try{await savePdfHandoff(result.blob,safePdfName(downloadName));router.push("/lab/pdf-compressor")}catch{setError("This browser could not pass the PDF to the compressor. Download it instead.");setHandoffBusy(false)}};
  const measuredCandidateSize=result?.candidateSize??result?.size??0;
  const measuredSaving=result&&mode==="compress"?((result.inputSize-measuredCandidateSize)/result.inputSize)*100:0;
  useMobileResultScroll(Boolean(result),resultRef);

  return <div className={styles.workspace}>
    <p className={styles.privacy}>Your PDFs are processed locally in this browser. They are not uploaded or stored.</p>
    <div className={styles.grid}>
      <section className={styles.panel}><h2>{mode==="merge"?"Add PDF files":"Choose a PDF"}</h2>
        <FileDropZone accept="application/pdf,.pdf" title={mode==="merge"?"Drop PDF files":"Drop a PDF"} restrictions={`${mode==="merge"?"PDF files only · up to 20 files":"PDF only"} · maximum 50 MB per file`} multiple={mode==="merge"} disabled={busyPhase!=="idle"} onFiles={files=>void add(files)}/>
        <ol className={styles.fileList}>{files.map((file,index)=>{const pages=pageCounts[fileKey(file)];return <li key={`${file.name}-${file.lastModified}-${index}`} draggable={mode==="merge"} data-dragging={dragIndex===index||undefined} onDragStart={event=>{setDragIndex(index);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",String(index))}} onDragOver={event=>{if(mode==="merge"){event.preventDefault();event.dataTransfer.dropEffect="move"}}} onDrop={event=>{event.preventDefault();const from=dragIndex??Number(event.dataTransfer.getData("text/plain"));moveTo(from,index);setDragIndex(null)}} onDragEnd={()=>setDragIndex(null)}><span><strong>{index+1}. {file.name}</strong><small>{pages===undefined?"Reading pages…":pages===null?"Page count unavailable":`${pages} ${pages===1?"page":"pages"}`} · {prettyBytes(file.size)}</small></span><span>{mode==="merge"&&<><button type="button" className={styles.button} data-quiet onClick={()=>move(index,-1)} disabled={index===0} aria-label={`Move ${file.name} up`}>↑</button><button type="button" className={styles.button} data-quiet onClick={()=>move(index,1)} disabled={index===files.length-1} aria-label={`Move ${file.name} down`}>↓</button></>}<button type="button" className={styles.button} data-quiet onClick={()=>{setFiles(current=>current.filter((_,item)=>item!==index));if(mode==="compress"){setLargeFileWarning(false);setLargeFileConfirmed(false)}}} aria-label={`Remove ${file.name}`}>×</button></span></li>})}</ol>
        {mode==="merge"&&files.length>1&&<p className={styles.inputHint}>Drag files to change their order. You can also use the arrow buttons.</p>}
        {mode==="compress"&&files.length>0&&<fieldset className={styles.pdfGoals}><legend>Select goal</legend><label><input type="radio" name="pdf-goal" checked={compressionGoal==="smallest"} onChange={()=>setCompressionGoal("smallest")}/><span><strong>Smallest file</strong><small>Keep any safe structural reduction the browser can make.</small></span></label><label><input type="radio" name="pdf-goal" checked={compressionGoal==="balanced"} onChange={()=>setCompressionGoal("balanced")}/><span><strong>Balanced</strong><small>Recommended · keep the original when the saving is below 2%.</small></span></label><label><input type="radio" name="pdf-goal" checked={compressionGoal==="best-quality"} onChange={()=>setCompressionGoal("best-quality")}/><span><strong>Best quality</strong><small>Keep the original PDF bytes unchanged.</small></span></label><p>This browser tool compacts PDF structure without reducing embedded image resolution. It does not expose DPI, font or JPEG controls because those changes are not reliably implemented here.</p></fieldset>}
        {largeFileWarning&&<aside className={styles.memoryWarning} aria-labelledby="large-pdf-warning"><strong id="large-pdf-warning">Large PDF detected</strong><p>Processing this file may use significant memory, especially on a phone or tablet. If this device cannot complete it, the file will stay here and will not be uploaded as a fallback.</p><label><input type="checkbox" checked={largeFileConfirmed} onChange={event=>{setLargeFileConfirmed(event.target.checked);if(event.target.checked)setError("")}}/> Continue processing on this device</label></aside>}
        <div className={styles.actions}><button type="button" className={styles.button} onClick={run} disabled={busyPhase!=="idle"}>{busyPhase==="preparing"?(mode==="compress"?"Preparing PDF compressor…":"Preparing PDF tools…"):busyPhase==="processing"?(mode==="compress"?"Compressing your PDF…":"Merging your PDFs…"):mode==="merge"?"Merge PDFs":"Compress PDF"}</button><button type="button" className={styles.button} data-quiet onClick={clear} disabled={busyPhase!=="idle"}>Clear</button></div><p className={styles.status} data-error={Boolean(error)} role="status" aria-live="polite">{busyPhase==="preparing"?(mode==="compress"?"Preparing PDF compressor…":"Preparing PDF tools…"):busyPhase==="processing"?(mode==="compress"?"Compressing your PDF…":"Merging your PDFs…"):error||note}</p>
      </section>
      <section ref={resultRef} className={styles.panel}><h2>Result</h2>{result?<>
        <div className={styles.resultHero} role="status"><span className={styles.resultLabel}>{mode==="merge"?"Merged PDF ready":"Done"}</span>{mode==="merge"?<><strong className={styles.resultName}>Merged PDF ready</strong><span className={styles.resultMetric}>{prettyBytes(result.size)}</span><p>{result.inputCount} files · {result.pages} pages</p></>:<><dl className={styles.compressionResult}><div><dt>Original</dt><dd>{prettyBytes(result.inputSize)}</dd></div><div><dt>Compressed</dt><dd>{prettyBytes(measuredCandidateSize)}</dd></div><div><dt>Saved</dt><dd>{measuredSaving>0?`${measuredSaving.toFixed(1)}%`:`0%`}</dd></div></dl><p>{result.compressionOutcome==="minimal"?`This PDF is already efficiently compressed. Only ${measuredSaving.toFixed(1)}% could be saved.`:result.compressionOutcome==="larger"?"The compressed version is larger than your original. Keep the original file.":result.compressionOutcome==="original"?"Best quality was selected, so the original PDF was kept unchanged.":`Saved ${measuredSaving.toFixed(1)}% without reducing embedded image resolution.`}</p></>}</div>
        {mode==="merge"&&<div className={styles.field}><label htmlFor="merged-pdf-name">Filename</label><input id="merged-pdf-name" value={downloadName} maxLength={120} onChange={event=>setDownloadName(event.target.value)} onBlur={()=>setDownloadName(safePdfName(downloadName))}/><small>Downloaded as {safePdfName(downloadName)}</small></div>}
        <dl className={styles.stats}><div><dt>Files</dt><dd>{result.inputCount}</dd></div><div><dt>Pages</dt><dd>{result.pages}</dd></div><div><dt>Size</dt><dd>{prettyBytes(result.size)}</dd></div><div><dt>Original total</dt><dd>{prettyBytes(result.inputSize)}</dd></div></dl>
        <div className={styles.actions}><a className={styles.button} href={result.url} download={safePdfName(downloadName)} aria-label={mode==="merge"?"Download merged PDF":result.usedOriginal?"Download original PDF":"Download compressed PDF"}>Download</a></div>
        {mode==="merge"?<div className={styles.resultLinks}><span>Need a smaller file?</span><button type="button" disabled={handoffBusy} onClick={()=>void compressMerged()}>{handoffBusy?"Opening…":"Compress this PDF →"}</button></div>:<p>Next: open the downloaded PDF and check its pages before sharing it.</p>}
      </>:<p>{mode==="merge"?"Your files are combined in the order shown.":"The smaller safe result will appear here."}</p>}{mode==="compress"&&<p>PDF compression here optimizes document structure. It does not reduce embedded image resolution, so already optimized or scanned PDFs may not become smaller.</p>}</section>
    </div>
  </div>;
}
