"use client";

import {useState} from "react";
import styles from "./simple-tools.module.css";

type PdfMode="merge"|"compress";
const prettyBytes=(bytes:number)=>bytes<1048576?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1048576).toFixed(1)} MB`;

export function PdfTool({mode}:{mode:PdfMode}){
  const [files,setFiles]=useState<File[]>([]),[result,setResult]=useState<{url:string;size:number;name:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[note,setNote]=useState("");
  const add=(incoming:FileList|File[])=>{const accepted=Array.from(incoming).filter(file=>file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf"));if(!accepted.length){setError("Choose PDF files.");return}if(accepted.some(file=>file.size>50*1024*1024)){setError("Each PDF must be smaller than 50 MB.");return}setFiles(current=>mode==="compress"?[accepted[0]]:[...current,...accepted].slice(0,20));setResult(null);setError("");setNote("")};
  const run=async()=>{if(mode==="merge"&&files.length<2){setError("Choose at least two PDFs to merge.");return}if(!files.length){setError("Choose a PDF first.");return}setBusy(true);setError("");setNote("");try{const {PDFDocument}=await import("pdf-lib");let bytes:Uint8Array;if(mode==="merge"){const output=await PDFDocument.create();for(const file of files){const input=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:false});const pages=await output.copyPages(input,input.getPageIndices());pages.forEach(page=>output.addPage(page))}bytes=await output.save({useObjectStreams:true,addDefaultPage:false});}else{const inputBytes=new Uint8Array(await files[0].arrayBuffer());const document=await PDFDocument.load(inputBytes,{ignoreEncryption:false,updateMetadata:false});const candidate=await document.save({useObjectStreams:true,addDefaultPage:false,objectsPerTick:50});bytes=candidate.length<inputBytes.length?candidate:inputBytes;setNote(candidate.length<inputBytes.length?"The PDF structure was compacted.":"This PDF is already compact. The original was kept because re-saving did not make it smaller.")}const blob=new Blob([bytes as BlobPart],{type:"application/pdf"});if(result)URL.revokeObjectURL(result.url);setResult({url:URL.createObjectURL(blob),size:blob.size,name:mode==="merge"?"merged.pdf":`${files[0].name.replace(/\.pdf$/i,"")}-compressed.pdf`});}catch{setError("This PDF could not be processed. It may be encrypted, damaged or unsupported.");}finally{setBusy(false)}};
  const move=(index:number,direction:-1|1)=>setFiles(current=>{const next=[...current],target=index+direction;if(target<0||target>=next.length)return current;[next[index],next[target]]=[next[target],next[index]];return next});
  const clear=()=>{if(result)URL.revokeObjectURL(result.url);setFiles([]);setResult(null);setError("");setNote("")};
  const inputSize=files.reduce((total,file)=>total+file.size,0);
  return <div className={styles.workspace}><p className={styles.privacy}>Your PDFs are processed locally in this browser. They are not uploaded or stored.</p><div className={styles.grid}><section className={styles.panel}><h2>{mode==="merge"?"Choose PDFs":"Choose a PDF"}</h2><label className={styles.drop} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();add(event.dataTransfer.files)}}><input type="file" accept="application/pdf,.pdf" multiple={mode==="merge"} onChange={event=>event.target.files&&add(event.target.files)}/><span><strong>Drop {mode==="merge"?"PDFs":"a PDF"} here</strong>or choose {mode==="merge"?"files":"a file"}</span></label><ol className={styles.fileList}>{files.map((file,index)=><li key={`${file.name}-${file.lastModified}-${index}`}><span>{file.name}<small>{prettyBytes(file.size)}</small></span><span>{mode==="merge"&&<><button type="button" className={styles.button} data-quiet onClick={()=>move(index,-1)} disabled={index===0} aria-label={`Move ${file.name} up`}>↑</button><button type="button" className={styles.button} data-quiet onClick={()=>move(index,1)} disabled={index===files.length-1} aria-label={`Move ${file.name} down`}>↓</button></>}<button type="button" className={styles.button} data-quiet onClick={()=>setFiles(current=>current.filter((_,item)=>item!==index))} aria-label={`Remove ${file.name}`}>×</button></span></li>)}</ol><div className={styles.actions}><button type="button" className={styles.button} onClick={run} disabled={busy}>{busy?"Working…":mode==="merge"?"Merge PDFs":"Compress PDF"}</button><button type="button" className={styles.button} data-quiet onClick={clear}>Clear</button></div><p className={styles.status} data-error={Boolean(error)} role="status">{error||note}</p></section><section className={styles.panel}><h2>Result</h2>{result?<><div className={styles.resultHero} role="status"><span className={styles.resultLabel}>Done</span><strong className={styles.resultName}>{result.name}</strong><span className={styles.resultMetric}>{prettyBytes(result.size)}</span><p>{mode==="merge"?`${files.length} PDFs were combined in the order shown.`:result.size<inputSize?`${Math.round((1-result.size/inputSize)*100)}% smaller than the original.`:"The original was already as small as the safe result."}</p></div><dl className={styles.stats}><div><dt>Original</dt><dd>{prettyBytes(inputSize)}</dd></div><div><dt>New size</dt><dd>{prettyBytes(result.size)}</dd></div></dl><div className={styles.actions}><a className={styles.button} href={result.url} download={result.name}>Download {result.name}</a></div><p>Next: open the downloaded PDF and check its pages before sharing it.</p></>:<p>{mode==="merge"?"Your files are combined in the order shown.":"The smaller safe result will appear here."}</p>}{mode==="compress"&&<p>PDF compression here optimizes document structure. It does not reduce embedded image resolution, so already optimized or scanned PDFs may not become smaller.</p>}</section></div></div>;
}
