"use client";

import {useCallback,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import styles from "./simple-tools.module.css";
import {savePdfHandoff,takePdfHandoff} from "@/lib/lab/pdf-handoff";

type PdfMode="merge"|"compress";
type PdfCompressionGoal="balanced"|"any-saving";
type PdfResult={url:string;blob:Blob;size:number;pages:number;inputCount:number;inputSize:number};
type PdfFailureCode="ENCRYPTED"|"CORRUPT"|"EMPTY"|"TOO_LARGE"|"MEMORY"|"UNSUPPORTED";
class PdfToolError extends Error{constructor(readonly code:PdfFailureCode){super(code)}}
const prettyBytes=(bytes:number)=>bytes<1048576?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1048576).toFixed(1)} MB`;
const fileKey=(file:File)=>`${file.name}:${file.size}:${file.lastModified}`;
const safePdfName=(value:string)=>{const base=value.trim().replace(/\.pdf$/i,"").replace(/[\\/:*?"<>|\u0000-\u001f]/g,"-").replace(/\s+/g," ").slice(0,116).trim();return `${base||"merged-document"}.pdf`};
const pdfFailureMessage=(failure:unknown)=>{
  if(failure instanceof PdfToolError){const messages:Record<PdfFailureCode,string>={ENCRYPTED:"This PDF is password protected.\n\nRemove the password first, then try again.",CORRUPT:"This PDF appears to be damaged.\n\nTry opening and saving it again in a PDF reader, then retry.",EMPTY:"This PDF has no pages.\n\nRemove it and choose a PDF that contains at least one page.",TOO_LARGE:"This PDF is too large to process safely here.\n\nChoose a file smaller than 50 MB.",MEMORY:"This browser ran out of memory while processing the PDF.\n\nTry fewer or smaller files, then run the merge again.",UNSUPPORTED:"This file is not a supported PDF.\n\nChoose a standard .pdf file and try again."};return messages[failure.code]}
  const detail=failure instanceof Error?failure.message.toLowerCase():"";
  if(/encrypt|password/.test(detail))return pdfFailureMessage(new PdfToolError("ENCRYPTED"));
  if(failure instanceof RangeError||/memory|allocation|array buffer/.test(detail))return pdfFailureMessage(new PdfToolError("MEMORY"));
  if(/invalid|corrupt|parse|header|xref|catalog/.test(detail))return pdfFailureMessage(new PdfToolError("CORRUPT"));
  return "This PDF could not be processed.\n\nIt may be damaged or use an unsupported PDF feature.";
};

export function PdfTool({mode}:{mode:PdfMode}){
  const router=useRouter();
  const [files,setFiles]=useState<File[]>([]),[result,setResult]=useState<PdfResult|null>(null),[downloadName,setDownloadName]=useState(mode==="merge"?"merged-document.pdf":"compressed.pdf"),[pageCounts,setPageCounts]=useState<Record<string,number|null>>({}),[dragIndex,setDragIndex]=useState<number|null>(null),[busy,setBusy]=useState(false),[handoffBusy,setHandoffBusy]=useState(false),[error,setError]=useState(""),[note,setNote]=useState("");
  const [compressionGoal,setCompressionGoal]=useState<PdfCompressionGoal>("balanced");
  useEffect(()=>()=>{if(result)URL.revokeObjectURL(result.url)},[result]);
  const readPageCounts=useCallback(async(incoming:File[])=>{const {PDFDocument}=await import("pdf-lib");const entries=await Promise.all(incoming.map(async file=>{try{const document=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:false});return [fileKey(file),document.getPageCount()] as const}catch{return [fileKey(file),null] as const}}));setPageCounts(current=>({...current,...Object.fromEntries(entries)}))},[]);
  useEffect(()=>{if(mode!=="compress")return;let active=true;void takePdfHandoff().then(file=>{if(!active||!file)return;setFiles([file]);void readPageCounts([file]);setDownloadName(`${file.name.replace(/\.pdf$/i,"")}-compressed.pdf`);setResult(null);setError("");setNote("Merged PDF received. Compress it when ready.")}).catch(()=>{});return()=>{active=false}},[mode,readPageCounts]);

  const add=(incoming:FileList|File[])=>{const selected=Array.from(incoming),accepted=selected.filter(file=>file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf"));if(!accepted.length){setError(pdfFailureMessage(new PdfToolError("UNSUPPORTED")));return}if(accepted.some(file=>file.size>50*1024*1024)){setError(pdfFailureMessage(new PdfToolError("TOO_LARGE")));return}void readPageCounts(accepted);setFiles(current=>mode==="compress"?[accepted[0]]:[...current,...accepted].slice(0,20));setResult(null);setError("");setNote(selected.length!==accepted.length?"Unsupported files were skipped. Only PDF files were added.":"")};
  const run=async()=>{if(mode==="merge"&&files.length<2){setError("Choose at least two PDFs to merge.");return}if(!files.length){setError("Choose a PDF first.");return}setBusy(true);setError("");setNote("");try{const {PDFDocument}=await import("pdf-lib");let bytes:Uint8Array,pages=0;if(mode==="merge"){const output=await PDFDocument.create();for(const file of files){if(file.size>50*1024*1024)throw new PdfToolError("TOO_LARGE");const input=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:false});if(input.getPageCount()===0)throw new PdfToolError("EMPTY");const copied=await output.copyPages(input,input.getPageIndices());copied.forEach(page=>output.addPage(page))}pages=output.getPageCount();bytes=await output.save({useObjectStreams:true,addDefaultPage:false});setDownloadName("merged-document.pdf")}else{if(files[0].size>50*1024*1024)throw new PdfToolError("TOO_LARGE");const inputBytes=new Uint8Array(await files[0].arrayBuffer());const document=await PDFDocument.load(inputBytes,{ignoreEncryption:false,updateMetadata:false});pages=document.getPageCount();if(pages===0)throw new PdfToolError("EMPTY");const candidate=await document.save({useObjectStreams:true,addDefaultPage:false,objectsPerTick:50}),saving=(inputBytes.length-candidate.length)/inputBytes.length;const keepCandidate=candidate.length<inputBytes.length&&(compressionGoal==="any-saving"||saving>=.02);bytes=keepCandidate?candidate:inputBytes;setDownloadName(`${files[0].name.replace(/\.pdf$/i,"")}-compressed.pdf`);setNote(keepCandidate?"The PDF structure was compacted.":candidate.length<inputBytes.length?"The available saving was below 2%, so the recommended mode kept the original.":"This PDF is already compact. The original was kept because re-saving did not make it smaller.")}const blob=new Blob([bytes as BlobPart],{type:"application/pdf"});if(result)URL.revokeObjectURL(result.url);setResult({url:URL.createObjectURL(blob),blob,size:blob.size,pages,inputCount:files.length,inputSize:files.reduce((total,file)=>total+file.size,0)})}catch(failure){setError(pdfFailureMessage(failure))}finally{setBusy(false)}};
  const move=(index:number,direction:-1|1)=>setFiles(current=>{const next=[...current],target=index+direction;if(target<0||target>=next.length)return current;[next[index],next[target]]=[next[target],next[index]];return next});
  const moveTo=(from:number,to:number)=>setFiles(current=>{if(from===to||from<0||to<0||from>=current.length||to>=current.length)return current;const next=[...current],[item]=next.splice(from,1);next.splice(to,0,item);return next});
  const clear=()=>{if(result)URL.revokeObjectURL(result.url);setFiles([]);setPageCounts({});setDragIndex(null);setResult(null);setDownloadName(mode==="merge"?"merged-document.pdf":"compressed.pdf");setCompressionGoal("balanced");setError("");setNote("")};
  const compressMerged=async()=>{if(!result)return;setHandoffBusy(true);setError("");try{await savePdfHandoff(result.blob,safePdfName(downloadName));router.push("/lab/pdf-compressor")}catch{setError("This browser could not pass the PDF to the compressor. Download it instead.");setHandoffBusy(false)}};

  return <div className={styles.workspace}>
    <p className={styles.privacy}>Your PDFs are processed locally in this browser. They are not uploaded or stored.</p>
    <div className={styles.grid}>
      <section className={styles.panel}><h2>{mode==="merge"?"Add PDF files":"Choose a PDF"}</h2>
        <label className={styles.drop} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();add(event.dataTransfer.files)}}><input type="file" accept="application/pdf,.pdf" multiple={mode==="merge"} onChange={event=>event.target.files&&add(event.target.files)}/><span><strong>{mode==="merge"?"Add PDF files":"Add a PDF"}</strong>or drop {mode==="merge"?"them":"it"} here</span></label>
        <ol className={styles.fileList}>{files.map((file,index)=>{const pages=pageCounts[fileKey(file)];return <li key={`${file.name}-${file.lastModified}-${index}`} draggable={mode==="merge"} data-dragging={dragIndex===index||undefined} onDragStart={event=>{setDragIndex(index);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",String(index))}} onDragOver={event=>{if(mode==="merge"){event.preventDefault();event.dataTransfer.dropEffect="move"}}} onDrop={event=>{event.preventDefault();const from=dragIndex??Number(event.dataTransfer.getData("text/plain"));moveTo(from,index);setDragIndex(null)}} onDragEnd={()=>setDragIndex(null)}><span><strong>{index+1}. {file.name}</strong><small>{pages===undefined?"Reading pages…":pages===null?"Page count unavailable":`${pages} ${pages===1?"page":"pages"}`} · {prettyBytes(file.size)}</small></span><span>{mode==="merge"&&<><button type="button" className={styles.button} data-quiet onClick={()=>move(index,-1)} disabled={index===0} aria-label={`Move ${file.name} up`}>↑</button><button type="button" className={styles.button} data-quiet onClick={()=>move(index,1)} disabled={index===files.length-1} aria-label={`Move ${file.name} down`}>↓</button></>}<button type="button" className={styles.button} data-quiet onClick={()=>setFiles(current=>current.filter((_,item)=>item!==index))} aria-label={`Remove ${file.name}`}>×</button></span></li>})}</ol>
        {mode==="merge"&&files.length>1&&<p className={styles.inputHint}>Drag files into the required order, or use the arrow buttons.</p>}
        {mode==="compress"&&files.length>0&&<fieldset className={styles.pdfGoals}><legend>Select goal</legend><label><input type="radio" name="pdf-goal" checked={compressionGoal==="balanced"} onChange={()=>setCompressionGoal("balanced")}/><span><strong>Balanced</strong><small>Recommended · keep the original when the saving is below 2%.</small></span></label><label><input type="radio" name="pdf-goal" checked={compressionGoal==="any-saving"} onChange={()=>setCompressionGoal("any-saving")}/><span><strong>Any safe saving</strong><small>Keep a structurally smaller file even when the difference is slight.</small></span></label><p>This browser tool compacts PDF structure without reducing embedded image resolution.</p></fieldset>}
        <div className={styles.actions}><button type="button" className={styles.button} onClick={run} disabled={busy}>{busy?"Working…":mode==="merge"?"Merge PDFs":"Compress PDF"}</button><button type="button" className={styles.button} data-quiet onClick={clear}>Clear</button></div><p className={styles.status} data-error={Boolean(error)} role="status">{error||note}</p>
      </section>
      <section className={styles.panel}><h2>Result</h2>{result?<>
        <div className={styles.resultHero} role="status"><span className={styles.resultLabel}>{mode==="merge"?"Merged PDF ready":"Done"}</span><strong className={styles.resultName}>{mode==="merge"?"Merged PDF ready":safePdfName(downloadName)}</strong><span className={styles.resultMetric}>{prettyBytes(result.size)}</span><p>{mode==="merge"?`${result.inputCount} files · ${result.pages} pages`:result.size<result.inputSize?`${Math.round((1-result.size/result.inputSize)*100)}% smaller than the original.`:"The original was already as small as the safe result."}</p></div>
        {mode==="merge"&&<div className={styles.field}><label htmlFor="merged-pdf-name">Filename</label><input id="merged-pdf-name" value={downloadName} maxLength={120} onChange={event=>setDownloadName(event.target.value)} onBlur={()=>setDownloadName(safePdfName(downloadName))}/><small>Downloaded as {safePdfName(downloadName)}</small></div>}
        <dl className={styles.stats}><div><dt>Files</dt><dd>{result.inputCount}</dd></div><div><dt>Pages</dt><dd>{result.pages}</dd></div><div><dt>Size</dt><dd>{prettyBytes(result.size)}</dd></div><div><dt>Original total</dt><dd>{prettyBytes(result.inputSize)}</dd></div></dl>
        <div className={styles.actions}><a className={styles.button} href={result.url} download={safePdfName(downloadName)}>{mode==="merge"?"Download PDF":`Download ${safePdfName(downloadName)}`}</a></div>
        {mode==="merge"?<div className={styles.resultLinks}><span>Need a smaller file?</span><button type="button" disabled={handoffBusy} onClick={()=>void compressMerged()}>{handoffBusy?"Opening…":"Compress this PDF →"}</button></div>:<p>Next: open the downloaded PDF and check its pages before sharing it.</p>}
      </>:<p>{mode==="merge"?"Your files are combined in the order shown.":"The smaller safe result will appear here."}</p>}{mode==="compress"&&<p>PDF compression here optimizes document structure. It does not reduce embedded image resolution, so already optimized or scanned PDFs may not become smaller.</p>}</section>
    </div>
  </div>;
}
