import Link from "next/link";

const topics=[
  {number:"01",title:"Title tags",body:"The title tag names a document in browser tabs, search results and many sharing contexts. A useful title identifies the page before the brand, matches what a visitor will actually find, and distinguishes the page from its neighbours. Length is a presentation constraint rather than a ranking formula: write for clarity first, then check that the important words are unlikely to be cut off.",guide:{href:"/guides/title-tags",label:"Read the title tag guide"}},
  {number:"02",title:"Meta descriptions",body:"A meta description is a proposed summary, not a promise about the exact search snippet. Search engines may replace it when another passage answers a query better. Give each important page a concise, page-specific explanation that helps a person decide whether the result is relevant; avoid lists of keywords and descriptions copied across the whole site.",guide:{href:"/guides/meta-descriptions",label:"Read the meta description guide"}},
  {number:"03",title:"Indexability",body:"A robots meta tag or X-Robots-Tag header can ask compatible search engines not to index a page. That is useful for staging pages, private utility screens and intentional duplicates, but damaging when left on a public landing page by mistake. The absence of a robots directive normally permits indexing—it does not guarantee discovery, crawling or inclusion."},
  {number:"04",title:"Canonical URLs",body:"A canonical identifies the preferred URL for substantially similar versions of a page. It helps consolidate signals when parameters, print views or duplicate paths expose the same content. Use one valid absolute URL, keep the protocol and host intentional, and remember that a canonical is a hint: redirects, internal links and sitemap entries should tell the same story.",guide:{href:"/guides/canonical-urls",label:"Understand canonical URLs"}},
  {number:"05",title:"Heading structure",body:"Headings create a readable outline for people scanning visually and for assistive technology navigating by section. Start with a clear primary heading, then use lower levels to describe real subsections rather than to achieve a font size. Multiple H1 elements are not automatically a disaster; clarity, sequence and meaningful text matter more than a simplistic count."},
  {number:"06",title:"Open Graph",body:"Open Graph metadata controls the title, description and image many platforms use when somebody shares a link. A complete preview makes the destination recognisable before the click. Images should be public, stable and designed to survive different crops; the visible page must still communicate well when a platform ignores the supplied metadata.",guide:{href:"/guides/open-graph",label:"Improve Open Graph previews"}},
  {number:"07",title:"Structured data",body:"JSON-LD can describe entities and relationships in a machine-readable form. It should reflect content that is genuinely present on the page and use an appropriate vocabulary. Valid JSON is only the first step: detected schema does not guarantee a rich result, and a page that has no relevant structured-data use case should not be penalised for omitting it.",guide:{href:"/guides/structured-data",label:"Learn structured data basics"}},
  {number:"08",title:"Image alternatives",body:"An alt attribute provides a text alternative when an image carries meaning. Describe the image's purpose in its specific context rather than mechanically naming every visible detail. Decorative images should usually use an intentional empty attribute—alt=\"\"—so assistive technology can skip them; the actual problem is an image with no alt decision at all."},
  {number:"09",title:"Mobile metadata",body:"The viewport declaration tells mobile browsers to use the device width instead of laying the page out on a virtual desktop canvas. It is necessary, but not sufficient, for a good phone experience. Responsive layout, readable type, reachable controls, sensible focus order and content that works without hover still require testing on narrow and zoomed viewports."},
  {number:"10",title:"Sitemaps",body:"An XML sitemap supplies a clean list of URLs a site wants crawlers to discover. It is especially useful for large, new or deeply nested sites, but it does not replace navigable internal links and does not force indexing. Keep entries canonical and current; for small well-linked sites, a missing sitemap is an improvement opportunity rather than an emergency.",guide:{href:"/guides/robots-txt",label:"Review robots.txt and sitemap discovery"}},
];

export function WebDoctorEducation(){return <section className="doctor-education" id="documentation" aria-labelledby="doctor-education-heading"><header><p className="eyebrow">LEARN THE SIGNALS</p><h2 id="doctor-education-heading">What does Web Doctor check?</h2><p>A report is more useful when you understand the decisions behind it. These are practical signals—not shortcuts, guarantees or universal ranking rules.</p></header><div className="doctor-education-topics">{topics.map(topic=><article key={topic.number}><span>{topic.number}</span><div><h3>{topic.title}</h3><p>{topic.body}</p>{topic.guide&&<Link href={topic.guide.href}>{topic.guide.label} <span aria-hidden="true">→</span></Link>}</div></article>)}</div><section className="doctor-limitations" aria-labelledby="doctor-limitations-heading"><header><p className="eyebrow">SCOPE, NOT PROMISES</p><h2 id="doctor-limitations-heading">What Web Doctor can and cannot check.</h2></header><div><article><h3>It reads the public response.</h3><p>Web Doctor analyses publicly accessible HTML, response headers and a small selection of public technical SEO files. It does not sign in, bypass access controls or crawl an entire website.</p></article><article><h3>It does not guarantee rankings.</h3><p>The score describes only the deterministic checks shown in the report. Search visibility also depends on relevance, competition, content quality, reputation, crawling and many systems this tool cannot observe.</p></article><article><h3>It does not replace Search Console.</h3><p>Web Doctor cannot show Google’s indexing decisions, search queries, manual actions, crawl history or submitted-sitemap status. Use Google Search Console for information available only to a verified site owner.</p></article><article><h3>It sees initial HTML.</h3><p>Some websites add metadata or content only after JavaScript executes. Those values may not exist in the server’s initial HTML response and can therefore be absent from this report. Web Doctor also does not measure real-user Core Web Vitals.</p></article></div></section><footer><p className="eyebrow">A SMALL GUIDE LIBRARY</p><p>Six substantial guides cover title tags, descriptions, canonical URLs, robots.txt, Open Graph and structured data. New guide pages will be published only when a topic has enough original examples and practical detail to deserve its own URL.</p></footer></section>;}
