import Link from "next/link";
import { LegalReviewNote } from "@/components/ui/legal-review-note";
import { PageIntro } from "@/components/ui/page-intro";
import { createPageMetadata } from "@/lib/seo/metadata";
import { ClarityPreferencesButton } from "@/components/analytics/clarity-preferences-button";
import { isClarityConsentRequired, normalizeClarityProjectId } from "@/lib/analytics/clarity-config";

export const metadata=createPageMetadata({title:"Cookies and Browser Storage",description:"Review the cookies, local browser storage and future consent requirements for Pujan Chapagain’s portfolio and Web Doctor.",path:"/cookies"});

export default function CookiesPage(){const clarityConfigured=Boolean(normalizeClarityProjectId(process.env.NEXT_PUBLIC_MICROSOFT_CLARITY_PROJECT_ID));const consentSetting=process.env.NEXT_PUBLIC_MICROSOFT_CLARITY_REQUIRE_CONSENT??process.env.NEXT_PUBLIC_MICROSOFT_CLARITY_ENABLED;const clarityRequireConsent=isClarityConsentRequired(consentSetting);return <main id="main"><PageIntro index="07" eyebrow="Cookies" title="A small, honest storage inventory." description="Essential browser storage supports site features. Microsoft Clarity can run without cookies or wait for your consent, depending on the configured mode." /><article className="privacy-body"><LegalReviewNote>Verify the live site with browser developer tools and the production hosting provider. Record an effective date and review this inventory whenever a vendor or script changes.</LegalReviewNote><section><p className="eyebrow">ANALYTICS CHOICE</p><h2>{clarityRequireConsent?"Clarity waits for permission.":"Clarity runs without analytics cookies."}</h2><p>{clarityRequireConsent?"When Microsoft Clarity is configured, no Clarity script or analytics request is loaded before you accept analytics. Rejecting keeps Clarity off. Advertising storage is not granted by this site.":"When Microsoft Clarity is configured in cookieless mode, it loads without showing a consent prompt and receives denied analytics and advertising storage signals. Microsoft reports each pageview as a separate session, so some reports are less accurate."}</p>{clarityConfigured&&clarityRequireConsent&&<ClarityPreferencesButton />}</section><section><p className="eyebrow">CLARITY COOKIES</p><h2>Only after analytics is accepted.</h2><p>Microsoft documents first-party Clarity cookies named <code>_clck</code> and <code>_clsk</code>, and related Microsoft-domain cookies including <code>CLID</code>, <code>ANONCHK</code>, <code>MR</code>, <code>MUID</code> and <code>SM</code>. Their availability and duration can depend on browser settings and Microsoft&apos;s service configuration.</p></section><section><p className="eyebrow">LOCAL STORAGE</p><h2>Preferences and recent checks stay on this device.</h2><p>When consent is required, the analytics choice is stored under <code>pujan:analytics-consent:v1</code> in localStorage. Web Doctor also saves analysed URL, score and check date in localStorage so recent checks can appear on the same device. You can remove individual checks or use Clear history in the tool.</p></section><section><p className="eyebrow">CONTROLS</p><h2>Your browser remains in control.</h2><p>You can change the analytics choice above when consent mode is enabled, or inspect, block and delete cookies and local storage through browser settings. Blocking storage can affect features that rely on it. For more context, read the <Link href="/privacy">Privacy notice</Link> or <Link href="/#contact">contact the owner</Link>.</p></section></article></main>;}
