import Link from "next/link";
import { LegalReviewNote } from "@/components/ui/legal-review-note";
import { PageIntro } from "@/components/ui/page-intro";
import { createPageMetadata } from "@/lib/seo/metadata";
import { ClarityPreferencesButton } from "@/components/analytics/clarity-preferences-button";
import { isClarityEnabled, normalizeClarityProjectId } from "@/lib/analytics/clarity-config";

export const metadata=createPageMetadata({title:"Cookies and Browser Storage",description:"Review the cookies, local browser storage and future consent requirements for Pujan Chapagain’s portfolio and Web Doctor.",path:"/cookies"});

export default function CookiesPage(){const clarityConfigured=isClarityEnabled(process.env.NEXT_PUBLIC_MICROSOFT_CLARITY_ENABLED)&&Boolean(normalizeClarityProjectId(process.env.NEXT_PUBLIC_MICROSOFT_CLARITY_PROJECT_ID));return <main id="main"><PageIntro index="07" eyebrow="Cookies" title="A small, honest storage inventory." description="Essential browser storage supports site features. Microsoft Clarity analytics remains off until you accept it." /><article className="privacy-body"><LegalReviewNote>Verify the live site with browser developer tools and the production hosting provider. Record an effective date and review this inventory whenever a vendor or script changes.</LegalReviewNote><section><p className="eyebrow">ANALYTICS CHOICE</p><h2>Clarity waits for permission.</h2><p>When Microsoft Clarity is enabled and its project is configured, no Clarity script or analytics request is loaded before you accept analytics. Rejecting keeps Clarity off. Advertising storage is not granted by this site.</p>{clarityConfigured&&<ClarityPreferencesButton />}</section><section><p className="eyebrow">CLARITY COOKIES</p><h2>Only after analytics is accepted.</h2><p>Microsoft documents first-party Clarity cookies named <code>_clck</code> and <code>_clsk</code>, and related Microsoft-domain cookies including <code>CLID</code>, <code>ANONCHK</code>, <code>MR</code>, <code>MUID</code> and <code>SM</code>. Their availability and duration can depend on browser settings and Microsoft&apos;s service configuration.</p></section><section><p className="eyebrow">LOCAL STORAGE</p><h2>Preferences and recent checks stay on this device.</h2><p>The analytics choice is stored under <code>pujan:analytics-consent:v1</code> in localStorage. Web Doctor also saves analysed URL, score and check date in localStorage so recent checks can appear on the same device. You can remove individual checks or use Clear history in the tool.</p></section><section><p className="eyebrow">CONTROLS</p><h2>Your browser remains in control.</h2><p>You can change the analytics choice above, or inspect, block and delete cookies and local storage through browser settings. Blocking storage can affect features that rely on it. For more context, read the <Link href="/privacy">Privacy notice</Link> or <Link href="/#contact">contact the owner</Link>.</p></section></article></main>;}
