import { assertPublicUrl } from "./dns-validation";
import type { FetchResult, PublicFile } from "./types/analysis";
import { Agent, fetch as protectedFetch } from "undici";
import type { LookupFunction } from "node:net";
import { SITE_URL } from "@/lib/site-config";

const HTML_LIMIT=3_000_000, FILE_LIMIT=200_000;
const IMAGE_PREVIEW_LIMIT=1_000_000;
const CONNECTION_TIMEOUT=4_000;
const USER_AGENT=`WebDoctor/1.0 (respectful SEO diagnostic; +${SITE_URL}/lab/web-doctor)`;
type PinnedAddress={address:string;family:4|6};
const pinnedAddresses=new Map<string,PinnedAddress[]>();
const pinnedLookup:LookupFunction=(hostname,options,callback)=>{const fail=(message:string)=>(callback as (error:Error)=>void)(new Error(message)),addresses=pinnedAddresses.get(hostname.toLowerCase().replace(/\.$/,""));if(!addresses?.length){fail("Hostname was not validated for this request.");return;}if(typeof options==="object"&&options.all){callback(null,addresses);return;}const preferred=typeof options==="object"&&options.family?addresses.find(item=>item.family===options.family):addresses[0];if(!preferred){fail("The validated hostname has no address in the requested family.");return;}callback(null,preferred.address,preferred.family);};
const protectedDispatcher=new Agent({connect:{lookup:pinnedLookup}});
function pinAddresses(hostname:string,addresses:PinnedAddress[]){const key=hostname.toLowerCase().replace(/\.$/,"");if(!pinnedAddresses.has(key)&&pinnedAddresses.size>=512){const oldest=pinnedAddresses.keys().next().value;if(oldest)pinnedAddresses.delete(oldest);}pinnedAddresses.delete(key);pinnedAddresses.set(key,addresses);}
const TLS_ERROR_CODES=new Set(["CERT_HAS_EXPIRED","CERT_NOT_YET_VALID","DEPTH_ZERO_SELF_SIGNED_CERT","ERR_TLS_CERT_ALTNAME_INVALID","SELF_SIGNED_CERT_IN_CHAIN","UNABLE_TO_GET_ISSUER_CERT","UNABLE_TO_VERIFY_LEAF_SIGNATURE"]);
function safeConnectionError(error:unknown){if(error instanceof DOMException&&(error.name==="TimeoutError"||error.name==="AbortError"))throw error;const code=typeof error==="object"&&error&&"cause" in error&&typeof error.cause==="object"&&error.cause&&"code" in error.cause?String(error.cause.code):"";if(TLS_ERROR_CODES.has(code)||code.startsWith("ERR_SSL_")||code.startsWith("ERR_TLS_"))throw new Error("The website's secure connection could not be verified.");throw new Error("We could not establish a reliable connection to that website.");}
async function readLimited(response:Response,limit:number){const declared=Number(response.headers.get("content-length")??0);if(declared>limit)throw new Error("The response is too large to analyse safely.");const reader=response.body?.getReader();if(!reader)throw new Error("The website returned an empty response.");const chunks:Uint8Array[]=[];let received=0;while(true){const {done,value}=await reader.read();if(done)break;received+=value.byteLength;if(received>limit){await reader.cancel();throw new Error("The response is too large to analyse safely.");}chunks.push(value);}const bytes=new Uint8Array(received);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}return new TextDecoder().decode(bytes);}
async function readBytesLimited(response:Response,limit:number){const declared=Number(response.headers.get("content-length")??0);if(declared>limit)throw new Error("The response is too large to analyse safely.");const reader=response.body?.getReader();if(!reader)throw new Error("The website returned an empty response.");const chunks:Uint8Array[]=[];let received=0;while(true){const {done,value}=await reader.read();if(done)break;received+=value.byteLength;if(received>limit){await reader.cancel();throw new Error("The response is too large to analyse safely.");}chunks.push(value);}const bytes=new Uint8Array(received);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}return bytes;}
async function request(initial:URL,options:{accept:string;timeout:number;redirects:number}){let url=initial;const totalSignal=AbortSignal.timeout(options.timeout);for(let count=0;count<=options.redirects;count++){const addresses=await assertPublicUrl(url);pinAddresses(url.hostname,addresses);const connectionController=new AbortController();const connectionTimer=setTimeout(()=>connectionController.abort(new DOMException("Connection timeout","TimeoutError")),CONNECTION_TIMEOUT);let response:Response;try{try{response=await protectedFetch(url,{redirect:"manual",signal:AbortSignal.any([totalSignal,connectionController.signal]),headers:{"User-Agent":USER_AGENT,Accept:options.accept,"Accept-Encoding":"gzip, deflate, br"},dispatcher:protectedDispatcher}) as unknown as Response;}catch(error){safeConnectionError(error);throw error;}}finally{clearTimeout(connectionTimer);}if(response.status>=300&&response.status<400){const location=response.headers.get("location");if(!location)throw new Error("The website returned an incomplete redirect.");url=new URL(location,url);continue;}return {response,url};}throw new Error("The website redirected too many times.");}
export async function safeFetchHtml(url:URL):Promise<FetchResult>{const started=performance.now();const {response,url:finalUrl}=await request(url,{accept:"text/html,application/xhtml+xml",timeout:10_000,redirects:5});if(response.status===401){await response.body?.cancel();throw new Error("The website requires authentication before it can be analysed.");}if(response.status===403){await response.body?.cancel();throw new Error("The website refused automated access.");}if(response.status===429){await response.body?.cancel();throw new Error("The website is temporarily limiting automated requests.");}if(response.status>=500){await response.body?.cancel();throw new Error("The website's server returned an error. Try again later.");}const contentType=(response.headers.get("content-type")??"").toLowerCase();if(!contentType.includes("text/html")&&!contentType.includes("application/xhtml+xml"))throw new Error("The URL did not return an HTML webpage.");return {html:await readLimited(response,HTML_LIMIT),url:finalUrl.toString(),statusCode:response.status,responseTimeMs:Math.round(performance.now()-started),headers:response.headers};}
export async function safeFetchPublicFile(url:URL,accept:string):Promise<PublicFile>{try{const result=await request(url,{accept,timeout:5_000,redirects:3});if(!result.response.ok)return {ok:false,status:result.response.status,text:"",url:result.url.toString()};const contentType=(result.response.headers.get("content-type")??"").toLowerCase();if(/^(video|audio|image)\//.test(contentType)||/(zip|octet-stream|pdf|gzip|rar|7z)/.test(contentType))return {ok:false,status:result.response.status,text:"",url:result.url.toString(),contentType};return {ok:true,status:result.response.status,text:await readLimited(result.response,FILE_LIMIT),url:result.url.toString(),contentType:contentType||undefined};}catch{return {ok:false,status:0,text:"",url:url.toString()};}}
export async function safeFetchImagePreview(url:URL){try{const result=await request(url,{accept:"image/avif,image/webp,image/png,image/jpeg,image/gif,image/x-icon,image/vnd.microsoft.icon",timeout:6_000,redirects:3});if(!result.response.ok)return null;const contentType=(result.response.headers.get("content-type")??"").split(";")[0].toLowerCase();if(!["image/avif","image/webp","image/png","image/jpeg","image/gif","image/x-icon","image/vnd.microsoft.icon"].includes(contentType))return null;const bytes=await readBytesLimited(result.response,IMAGE_PREVIEW_LIMIT);return {url:result.url.toString(),dataUrl:`data:${contentType};base64,${Buffer.from(bytes).toString("base64")}`};}catch{return null;}}
